### ISSUE TITLE
Cannot build the echo server on Ubuntu 14.04.3

### ISSUE THREAD

**Issue by David-Haim** [facebook/proxygen#73]
david@david-VirtualBox:~/Documents/Proxigen/proxygen-master/proxygen/httpserver/samples/echo$ g++ -std=c++11 -o my_echo EchoServer.cpp EchoHandler.cpp -lproxygenhttpserver -lfolly -lglog -lgflags -pthread
EchoServer.cpp:14:44: fatal error: proxygen/httpserver/HTTPServer.h: No such file or directory
 #include <proxygen/httpserver/HTTPServer.h>
                                            ^
compilation terminated.
In file included from EchoHandler.cpp:10:0:
EchoHandler.h:13:48: fatal error: proxygen/httpserver/RequestHandler.h: No such file or directory
 #include <proxygen/httpserver/RequestHandler.h>
                                                ^
compilation terminated.

This was after I built the dependencies with the suggested ./deps.sh && ./reinstall.sh command

**Comment by mjs6643** [comment]
When did you try building Proxygen? There's been a bug in Wangle the past few days that's breaking the Proxygen build. I opened up a ticket and they should have a fix shortly.

**Comment by David-Haim** [comment]
hmm... probably it is the issue. I will update as soon as the fix is on.

**Comment by mjs6643** [comment]
You can track that here: https://github.com/facebook/wangle/issues/18

**Comment by xiaosophiawang** [comment]
Hi David, thanks for opening the issue! We have fixed wangle today and I'm able to build on Ubuntu 14.04 and 15.04. Let us know if it still doesn't work for you. Thanks!

**Comment by rstims** [comment]
root@dvb:~/proxygen/proxygen/httpserver/samples/echo# g++ -std=c++11 -o my_echo EchoServer.cpp EchoHandler.cpp -lproxygenhttpserver -lfolly -lglog -lgflags -pthread
EchoServer.cpp:14:44: fatal error: proxygen/httpserver/HTTPServer.h: No such file or directory
 #include <proxygen/httpserver/HTTPServer.h>
                                            ^
compilation terminated.
In file included from EchoHandler.cpp:10:0:
EchoHandler.h:13:48: fatal error: proxygen/httpserver/RequestHandler.h: No such file or directory
 #include <proxygen/httpserver/RequestHandler.h>
                                                ^
compilation terminated.


This is what I received when I tried to build the server after deps and reinstall.
