### ISSUE TITLE
ld: error: undefined reference due to --no-allow-shlib-undefined: vtable for fizz::openssl::OpenSSLECKeyExchange

### ISSUE THREAD

**Issue by yurivict** [facebook/proxygen#502]
Version 2024.06.03.00 fails to build with fizz-2024.06.03.00:
```
ld: error: undefined reference due to --no-allow-shlib-undefined: vtable for fizz::openssl::OpenSSLECKeyExchange
>>> referenced by /usr/local/lib/libfizz.so.1.0.0

ld: error: undefined reference due to --no-allow-shlib-undefined: fizz::openssl::OpenSSLECKeyExchange::setPrivateKey(std::__1::unique_ptr<evp_pkey_st, folly::static_function_deleter<evp_pkey_st, &EVP_PKEY_free>>)
>>> referenced by /usr/local/lib/libfizz.so.1.0.0
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Clang-18
FreeBSD 14.0

**Comment by afrind** [comment]
I think this has been fixed, please pull from trunk and try again
